local source = debug.getinfo(1, "S").source:sub(2)
local root = vim.fn.fnamemodify(source, ":p:h:h")
vim.opt.runtimepath:prepend(root)

local function equal(actual, expected, message)
  assert(vim.deep_equal(actual, expected), message or vim.inspect({ actual, expected }))
end

local scope = require("archlens.scope")
local project = vim.fn.tempname()
vim.fn.mkdir(project .. "/internal", "p")
vim.fn.mkdir(project .. "/vendor/example", "p")
vim.fn.mkdir(project .. "/node_modules/example", "p")
vim.fn.mkdir(project .. "/target/debug", "p")
vim.fn.mkdir(project .. "/target/vendor", "p")
vim.fn.mkdir(project .. "/generated/api", "p")
vim.fn.mkdir(project .. "/vendor/generated", "p")
vim.fn.mkdir(project .. "/custom/cache", "p")

local cache = {}
equal(scope.classify(project, project .. "/internal/main.go", {}, cache), "project")
equal(scope.classify(project, project .. "/vendor/example/main.go", {}, cache), "vendored")
equal(scope.classify(project, project .. "/node_modules/example/index.js", {}, cache), "vendored")
equal(scope.classify(project, project .. "/_opam/lib/example.ml", {}, cache), "vendored")
equal(scope.classify(project, project .. "/target/debug/build.rs", {}, cache), "generated")
equal(scope.classify(project, project .. "/_build/default/example.ml", {}, cache), "generated")
equal(scope.classify(project, project .. "/generated/api/client.go", {}, cache), "generated")
equal(
  scope.classify(
    project,
    project .. "/target/vendor/client.go",
    { include_generated = true },
    cache
  ),
  "vendored",
  "enabling generated paths must not expose a nested vendored path"
)
equal(
  scope.classify(
    project,
    project .. "/vendor/generated/client.go",
    { include_vendored = true },
    cache
  ),
  "generated",
  "enabling vendored paths must not expose a nested generated path"
)
equal(
  scope.classify(
    project,
    project .. "/custom/cache/data.go",
    { exclude = { "custom/cache" } },
    cache
  ),
  "excluded"
)
equal(scope.classify(project, vim.fs.dirname(project) .. "/external.go", {}, cache), "external")

equal(
  scope.classify(project, project .. "/internal/zz_generated.deepcopy.go", {}, cache),
  "generated"
)
equal(scope.classify(project, project .. "/internal/service.gen.go", {}, cache), "generated")
equal(scope.classify(project, project .. "/internal/service.pb.go", {}, cache), "generated")

local generated_by_header = project .. "/internal/api.go"
vim.fn.writefile(
  { "// Code generated by fixture. DO NOT EDIT.", "package internal" },
  generated_by_header
)
equal(scope.classify(project, generated_by_header, {}, cache), "generated")
local ordinary = project .. "/internal/ordinary.go"
vim.fn.writefile({
  "package internal",
  "// This documentation explains the @generated marker without declaring this file generated.",
}, ordinary)
equal(scope.classify(project, ordinary, {}, cache), "project")

scope.clear_cache()
local original_fs_stat = vim.uv.fs_stat
local stat_calls = 0
vim.uv.fs_stat = function(path, ...)
  if path == ordinary then
    stat_calls = stat_calls + 1
  end
  return original_fs_stat(path, ...)
end
local first_build_cache = {}
equal(scope.classify(project, ordinary, {}, first_build_cache), "project")
equal(scope.classify(project, ordinary, {}, first_build_cache), "project")
local second_build_cache = {}
equal(scope.classify(project, ordinary, {}, second_build_cache), "project")
equal(scope.classify(project, ordinary, {}, second_build_cache), "project")
vim.uv.fs_stat = original_fs_stat
equal(stat_calls, 2, "each render should stat a repeated source path at most once")

for _, kind in ipairs({ "external", "vendored", "generated", "excluded" }) do
  equal(scope.visible(kind, {}), false, kind .. " should be hidden by default")
end
equal(scope.visible("project", {}), true)
equal(scope.visible("external", { include_external = true }), true)
equal(scope.visible("vendored", { include_vendored = true }), true)
equal(scope.visible("generated", { include_generated = true }), true)
equal(scope.visible("excluded", { include_generated = true }), false)

print("archlens project scope tests passed")
vim.cmd("quitall")
